services:
  bot:
    build: src
    container_name: boardgame_discord_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - logs:/logs/
    develop:
      watch:
        - action: rebuild
          path: src

volumes:
  logs:
    driver: local
