[project]
name = "boardgame-discord-bot"
version = "5.1.2"
description = "Boardgame discord bot."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "discord-py>=2.7.1",
    "jinja2>=3.1.6",
    "pydantic>=2.13.4",
    "pydantic-extra-types>=2.11.1",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
]
